<div class="page-header"><div><h2>Support Center</h2><p>Track internal incidents, escalations, and SaaS support issues in one operational queue.</p></div></div>
<div class="card"><form method="get" class="stack-form">
<input type="hidden" name="page" value="support">
<div class="grid grid-3">
<select name="status"><option value="">All Statuses</option><?php foreach (['Open','Investigating','Waiting','Resolved','Closed'] as $status): ?><option value="<?= e($status) ?>" <?= (($filters['status'] ?? '') === $status) ? 'selected' : '' ?>><?= e($status) ?></option><?php endforeach; ?></select>
<select name="priority"><option value="">All Priorities</option><?php foreach (['Low','Normal','High','Urgent'] as $priority): ?><option value="<?= e($priority) ?>" <?= (($filters['priority'] ?? '') === $priority) ? 'selected' : '' ?>><?= e($priority) ?></option><?php endforeach; ?></select>
<input type="text" name="q" placeholder="Search title/details" value="<?= e($filters['q'] ?? '') ?>">
</div><button type="submit">Apply Filters</button></form></div>
<?php if (\App\Core\Auth::can('support','create')): ?>
<div class="card"><h3>Create Ticket</h3><form method="post" class="stack-form"><?= csrf_field() ?><input type="hidden" name="action" value="create"><div class="grid grid-2"><input type="text" name="title" placeholder="Ticket title" required><input type="text" name="category_name" placeholder="Category" value="Operations"></div><div class="grid grid-3"><select name="priority_name"><?php foreach (['Low','Normal','High','Urgent'] as $priority): ?><option value="<?= e($priority) ?>"><?= e($priority) ?></option><?php endforeach; ?></select><select name="status_name"><?php foreach (['Open','Investigating','Waiting','Resolved'] as $status): ?><option value="<?= e($status) ?>"><?= e($status) ?></option><?php endforeach; ?></select><select name="owner_user_id"><option value="">Unassigned</option><?php foreach ($users as $user): ?><option value="<?= e((string)$user['id']) ?>"><?= e($user['full_name']) ?></option><?php endforeach; ?></select></div><textarea name="detail_text" placeholder="Describe the issue or request"></textarea><button type="submit">Create Ticket</button></form></div>
<?php endif; ?>
<div class="card"><table><thead><tr><th>ID</th><th>Title</th><th>Category</th><th>Priority</th><th>Status</th><th>Owner</th><th>Created</th><th>Actions</th></tr></thead><tbody><?php foreach ($tickets as $ticket): ?><tr><td><?= e((string)$ticket['id']) ?></td><td><?= e($ticket['title']) ?><div class="meta"><?= e((string)($ticket['detail_text'] ?? '')) ?></div></td><td><?= e($ticket['category_name']) ?></td><td><span class="tag"><?= e($ticket['priority_name']) ?></span></td><td><?= e($ticket['status_name']) ?></td><td><?= e((string)($ticket['owner_user_id'] ?? '')) ?></td><td><?= e($ticket['created_at']) ?></td><td><?php if (\App\Core\Auth::can('support','edit')): ?><form method="post" style="display:inline-block"><?= csrf_field() ?><input type="hidden" name="action" value="status"><input type="hidden" name="id" value="<?= e((string)$ticket['id']) ?>"><select name="status_name"><?php foreach (['Open','Investigating','Waiting','Resolved','Closed'] as $status): ?><option value="<?= e($status) ?>" <?= $ticket['status_name'] === $status ? 'selected' : '' ?>><?= e($status) ?></option><?php endforeach; ?></select><button type="submit">Save</button></form><?php endif; ?> <?php if (\App\Core\Auth::can('support','delete')): ?><form method="post" style="display:inline-block" onsubmit="return confirm('Delete this ticket?')"><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= e((string)$ticket['id']) ?>"><button type="submit">Delete</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
