<div class="page-header"><div><h2>API Token Center</h2><p>Create, rotate, and revoke scoped bearer tokens for integrations. Plaintext tokens are only shown once.</p></div></div>
<?php if (!empty($revealedToken)): ?>
<div class="card"><h3>Copy this token now</h3><div class="note">Store this token securely. It will not be shown again after this page load.</div><div class="code-block"><?= e($revealedToken['plain_text']) ?></div><div class="muted">Scopes: <?= e($revealedToken['scope_text']) ?></div></div>
<?php endif; ?>
<div class="grid-two">
<div class="card"><h3>Create Token</h3><form method="post" class="stack-form"><?= csrf_field() ?><input type="hidden" name="action" value="create"><input name="token_name" placeholder="Token Name" required><input name="scope_text" value="clients:read,clients:write,leads:read,deals:read,tasks:read,communications:read" placeholder="Scopes (comma separated)"><input type="datetime-local" name="expires_at"><button type="submit">Create Token</button></form><p class="muted">Example scopes: <code>clients:read</code>, <code>clients:write</code>, <code>communications:read</code>, <code>deals:*</code>, <code>*</code></p></div>
<div class="card"><h3>Token Usage</h3><ul><li>Send as <code>Authorization: Bearer TOKEN</code> or <code>X-API-Key</code></li><li>Supported resources: clients, leads, deals, tasks, communications</li><li>Write methods require matching <code>:write</code> scope</li><li>Legacy single-token auth remains supported for compatibility</li></ul></div>
</div>
<div class="card"><table><thead><tr><th>Name</th><th>Prefix</th><th>Scopes</th><th>Last Used</th><th>Expires</th><th>Status</th><th></th></tr></thead><tbody><?php foreach ($tokens as $row): ?><tr><td><?= e($row['token_name']) ?></td><td><code><?= e($row['token_prefix']) ?></code></td><td class="muted"><?= e($row['scope_text']) ?></td><td><?= e((string)($row['last_used_at'] ?? 'Never')) ?></td><td><?= e((string)($row['expires_at'] ?? 'No expiry')) ?></td><td><?= !empty($row['revoked_at']) ? 'Revoked' : 'Active' ?></td><td class="table-actions"><?php if (empty($row['revoked_at']) && App\Core\Auth::can('tokens','edit')): ?><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="rotate"><input type="hidden" name="id" value="<?= e((string)$row['id']) ?>"><button type="submit">Rotate</button></form><?php endif; ?><?php if (empty($row['revoked_at']) && App\Core\Auth::can('tokens','delete')): ?><form method="post" onsubmit="return confirm('Revoke this token?');"><?= csrf_field() ?><input type="hidden" name="action" value="revoke"><input type="hidden" name="id" value="<?= e((string)$row['id']) ?>"><button class="btn-danger" type="submit">Revoke</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
