<div class="page-header"><div><h2>AI Workspace</h2><p>Lead scoring, client summaries, and communication drafting with built-in intelligence hooks.</p></div></div>
<div class="grid-three">
<div class="card"><h3>Score Lead</h3><form method="post" class="stack-form"><?= csrf_field() ?><input type="hidden" name="action" value="score_lead"><select name="lead_id"><?php foreach ($leads as $lead): ?><option value="<?= e((string)$lead['id']) ?>"><?= e($lead['lead_name']) ?> · <?= e($lead['company_name']) ?></option><?php endforeach; ?></select><button type="submit">Score Lead</button></form></div>
<div class="card"><h3>Summarize Client</h3><form method="post" class="stack-form"><?= csrf_field() ?><input type="hidden" name="action" value="summarize_client"><select name="client_id"><?php foreach ($clients as $client): ?><option value="<?= e((string)$client['id']) ?>"><?= e($client['company_name']) ?> · <?= e($client['contact_name']) ?></option><?php endforeach; ?></select><button type="submit">Generate Summary</button></form></div>
<div class="card"><h3>Draft Email</h3><form method="post" class="stack-form"><?= csrf_field() ?><input type="hidden" name="action" value="draft_email"><select name="tone"><?php foreach (['Professional','Friendly','Urgent'] as $tone): ?><option value="<?= e($tone) ?>"><?= e($tone) ?></option><?php endforeach; ?></select><textarea name="context" placeholder="Context for the email"></textarea><button type="submit">Draft Email</button></form></div>
</div>
<?php if (!empty($result)): ?>
<div class="card"><h3>Result</h3><?php if (!empty($result['summary'])): ?><div class="note"><?= e($result['summary']) ?></div><?php endif; ?><?php if (isset($result['score'])): ?><div class="note">Score: <strong><?= e((string)$result['score']) ?></strong><br><?= e($result['explanation'] ?? '') ?></div><?php endif; ?><?php if (!empty($result['subject']) || !empty($result['body'])): ?><div class="code-block">Subject: <?= e($result['subject'] ?? '') ?>

<?= e($result['body'] ?? '') ?></div><?php endif; ?></div>
<?php endif; ?>
<div class="card"><h3>AI Activity Log</h3><table><thead><tr><th>Tool</th><th>Input</th><th>Output</th><th>When</th></tr></thead><tbody><?php foreach ($logs as $log): ?><tr><td><?= e($log['tool_name']) ?></td><td><?= e(substr((string)$log['input_text'],0,90)) ?></td><td><?= e(substr((string)$log['output_text'],0,140)) ?></td><td><?= e($log['created_at']) ?></td></tr><?php endforeach; ?></tbody></table></div>
