<?php
namespace App\Controllers;

use App\Core\Auth;
use App\Core\View;
use App\Models\Commission;
use App\Models\Deal;
use App\Models\Lead;
use App\Models\Message;
use App\Models\Notification;
use App\Models\Report;
use App\Models\Task;
use App\Models\User;
use App\Services\WorkflowEngine;

class ReportController {
    public function __construct(private \PDO $db) {}

    public function index(): void {
        Auth::requirePermission('reports', 'view');
        $filters = [
            'date_from' => $_GET['date_from'] ?? '',
            'date_to' => $_GET['date_to'] ?? '',
            'user_id' => $_GET['user_id'] ?? '',
        ];

        if (isset($_GET['export']) && $_GET['export'] !== '') {
            $this->export((string) $_GET['export'], $filters);
            return;
        }

        $reports = (new Report($this->db))->list();
        $users = (new User($this->db))->assigneeOptions();
        $deals = $this->filterRows((new Deal($this->db))->list(), $filters, 'owner_user_id', 'updated_at');
        $commissions = $this->filterRows((new Commission($this->db))->list(), $filters, 'agent_user_id', 'updated_at');
        $messages = $this->filterRows((new Message($this->db))->list(), $filters, 'created_by', 'updated_at');
        $leads = $this->filterRows((new Lead($this->db))->list(), $filters, 'assigned_user_id', 'updated_at');
        $tasks = $this->filterRows((new Task($this->db))->list(), $filters, 'assigned_user_id', 'updated_at');
        $queue = (new WorkflowEngine($this->db))->queueSnapshot(100);

        $summary = [
            'deal_value' => array_sum(array_map(fn ($row) => (float) $row['amount'], $deals)),
            'commission_due' => array_sum(array_map(fn ($row) => ($row['payout_status'] ?? '') !== 'Paid' ? (float) $row['amount'] : 0.0, $commissions)),
            'lead_count' => count($leads),
            'task_count' => count($tasks),
            'message_count' => count($messages),
            'workflow_queue' => count($queue),
        ];

        $pipeline = [];
        foreach ($deals as $deal) {
            $stage = $deal['stage'] ?: 'Unknown';
            $pipeline[$stage] = ($pipeline[$stage] ?? 0) + (float) $deal['amount'];
        }
        arsort($pipeline);

        $commissionByAgent = [];
        foreach ($commissions as $commission) {
            $name = $commission['agent_name'] ?: 'Unassigned';
            $commissionByAgent[$name] = ($commissionByAgent[$name] ?? 0.0) + (float) $commission['amount'];
        }
        arsort($commissionByAgent);

        $activityByChannel = [];
        foreach ($messages as $message) {
            $channel = $message['channel'] ?: 'Unknown';
            $activityByChannel[$channel] = ($activityByChannel[$channel] ?? 0) + 1;
        }
        arsort($activityByChannel);

        View::render('reports/index', compact('reports', 'summary', 'pipeline', 'commissionByAgent', 'activityByChannel', 'filters', 'users'));
    }

    private function filterRows(array $rows, array $filters, string $userColumn, string $dateColumn): array {
        return array_values(array_filter($rows, function (array $row) use ($filters, $userColumn, $dateColumn) {
            if (!empty($filters['user_id']) && (int) ($row[$userColumn] ?? 0) !== (int) $filters['user_id']) {
                return false;
            }
            if (!empty($filters['date_from']) && !empty($row[$dateColumn]) && substr((string) $row[$dateColumn], 0, 10) < $filters['date_from']) {
                return false;
            }
            if (!empty($filters['date_to']) && !empty($row[$dateColumn]) && substr((string) $row[$dateColumn], 0, 10) > $filters['date_to']) {
                return false;
            }
            return true;
        }));
    }

    private function export(string $resource, array $filters): void {
        $allowed = [
            'deals' => $this->filterRows((new Deal($this->db))->list(), $filters, 'owner_user_id', 'updated_at'),
            'leads' => $this->filterRows((new Lead($this->db))->list(), $filters, 'assigned_user_id', 'updated_at'),
            'tasks' => $this->filterRows((new Task($this->db))->list(), $filters, 'assigned_user_id', 'updated_at'),
            'communications' => $this->filterRows((new Message($this->db))->list(), $filters, 'created_by', 'updated_at'),
            'commissions' => $this->filterRows((new Commission($this->db))->list(), $filters, 'agent_user_id', 'updated_at'),
        ];
        if (!isset($allowed[$resource])) {
            http_response_code(404);
            exit('Export not available.');
        }
        (new Notification($this->db))->create([
            'title' => 'Report exported',
            'message_text' => strtoupper($resource) . ' export generated by ' . (Auth::user()['full_name'] ?? 'system'),
            'level_name' => 'success',
            'link_url' => 'index.php?page=reports',
        ]);
        audit_log($this->db, 'reports', 'export', null, 'CSV export generated for ' . $resource);
        header('Content-Type: text/csv; charset=utf-8');
        header('Content-Disposition: attachment; filename="' . $resource . '_report_' . date('Ymd_His') . '.csv"');
        $out = fopen('php://output', 'w');
        $rows = $allowed[$resource];
        if (!empty($rows)) {
            fputcsv($out, array_keys($rows[0]));
            foreach ($rows as $row) {
                fputcsv($out, $row);
            }
        }
        fclose($out);
        exit;
    }
}
